---
# handlers file for postgres
- name: restart apache2
  systemd:
    state: restarted
    daemon_reload: yes
    name: apache2
    
- name: restart postgres
  systemd:
    state: restarted
    daemon_reload: yes
    name: postgresql
    
    
- name: restart repmgrd
  systemd:
    state: restarted
    daemon_reload: yes
    name: repmgrd